version: '2.0'

services:
  robot-framework-target:
    tty: true
    image: rpartapsing/dsh:part1 #dockerrfpy27
    volumes:
      - ./Testcases:/robot/Testcases
      - ./requirements:/robot/requirements
      - ./Testresults:/robot/Testresults
    container_name: dockerrfpy27
    working_dir: /robot
    external_links:
      - dkafka
    entrypoint: bash -lc "source venv/bin/activate && pybot -d Testresults Testcases/"
    #entrypoint: sleep 1h